name: Code Coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
    - run: bundle install
    - run: bundle exec rspec
    - name: Upload to Codecov
      uses: codecov/codecov-action@v4

